let key =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJhZTkzNDUzOC0zNzNjLTRiNjgtODEyNC03MGFkN2Q5NmJkYTkiLCJpZCI6MTgwOTMyLCJpYXQiOjE3MDEwNzMzMzh9.LChUlu3p74pFuj6kFCyLkdDZ--9ax2cttsopv1O4nb0";

Cesium.Ion.defaultAccessToken = key;
